test_name: Customer
target:
  api_server:  api.rs2.usw2.rockset.com
  iterations: 1
  execution_mode: serial
  overrides:
queries:
  - name: Count 1
    sql: >+
      SELECT
          COUNT(*)
      FROM 
          _events
    parameters: []
    paginate: False
    initial_paginate_response_doc_count: 1000
    drop_results: False